inherit_from:
  - ~/configs/.rubocop.yml

AllCops:
  Include:
    - 'lib/**/*.rb'
  Exclude:
    - 'test/**/*'

Layout/AccessModifierIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
