# see also https://github.com/whitequark/parser/blob/master/.github/workflows/test.yml
name: Rake

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.4", "3.2"]
        gemfile:
          - Gemfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Bundle install
        run: |
          bundle config set frozen false
          bundle config path /home/runner/bundle
          bundle install
          bundle update
      - name: Build and test with Rake
        run: bundle exec rake
