# adapted from https://github.com/whitequark/parser/blob/master/.github/workflows/test.yml
name: Tests

on: [push]
#on:
#  push:
#    branches:
#    - master
#  pull_request:

jobs:
  test:
#    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
#        ruby: ["2.4.10", "2.5.9", "2.6.7", "2.7.3", "3.0.1", "jruby-9.2"]
#        ruby: ["2.7.2", "2.7.3", "3.0.1"]
        ruby: ["2.7.2"]
        test_command: ["bundle exec rake test"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ hashFiles('../Gemfile') }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle install
        bundle update
    - name: Run tests
      run: |
        ${{ matrix.test_command }}
